ROOT_NODE_NAME = "root"
CHILD_NODE_NAME = "child"

ROW_COUNT = 6
COLUMN_COUNT = 7

INITIAL_ASSIGNMENTS_DEPTH = 3

HUMAN_PLAYER_MARK = "P"
HUMAN_PLAYER_TURN = 0
HUMAN_VICTORY_MESSAGE = "Pobjeda igraca"

COMPUTER_PLAYER_MARK = "C"
COMPUTER_PLAYER_TURN = 1
COMPUTER_VICTORY_MESSAGE = "Pobjeda racunala"

EMPTY_SPACE_MARK = "="

TIED_RESULT_MESSAGE = "Izjednaceno"

MASTER_RANK = 0
